particlesJS("particles-js", {
    "particles":{
        "number":{
            "value":6,
            "density":{
                "enable":true,
                "value_area":641.3648243462092
            }
        },
        "color":{
            "value":"#79e7ff"
        },
        "shape":{
            "type":"circle",
            "stroke":{
                "width":0,
                "color":"#ffffff"
            },
            "polygon":{
                "nb_sides":4
            },
            "image":{
                "src":"img/github.svg",
                "width":100,
                "height":100
            }
        },
        "opacity":{
            "value":0.6413648243462091,
            "random":true,
            "anim":{
                "enable":false,
                "speed":1,
                "opacity_min":0.1,
                "sync":false
            }
        },
        "size":{
            "value":280.5971106514665,
            "random":true,
            "anim":{
                "enable":true,
                "speed":9.744926547616142,
                "size_min":17.053621458328248,
                "sync":false
            }
        },
        "line_linked":{
            "enable":false,
            "distance":208.44356791251798,
            "color":"#4169e1",
            "opacity":0.4649894976510016,
            "width":7.536036686067957
        },
        "move":{
            "enable":true,
            "speed":6.413648243462092,
            "direction":"none",
            "random":false,
            "straight":false,
            "out_mode":"out",
            "bounce":false,
            "attract":{
                "enable":false,
                "rotateX":600,
                "rotateY":1200
            }
        }
    },
    "interactivity":{
        "detect_on":"canvas",
        "events":{
            "onhover":{
                "enable":false,
                "mode":"grab"
            },
            "onclick":{
                "enable":false,
                "mode":"push"
            },
            "resize":true
        },
        "modes":{
            "grab":{
                "distance":400,
                "line_linked":{
                    "opacity":1
                }
            },
            "bubble":{
                "distance":400,
                "size":40,
                "duration":2,
                "opacity":8,
                "speed":3
            },
            "repulse":{
                "distance":200,
                "duration":0.4
            },
            "push":{
                "particles_nb":4
            },
            "remove":{
                "particles_nb":2
            }
        }
    },
    "retina_detect":true
});var count_particles, stats, update; stats = new Stats; stats.setMode(0); stats.domElement.style.position = 'absolute'; stats.domElement.style.left = '0px'; stats.domElement.style.top = '0px'; document.body.appendChild(stats.domElement); count_particles = document.querySelector('.js-count-particles'); update = function() { stats.begin(); stats.end(); if (window.pJSDom[0].pJS.particles && window.pJSDom[0].pJS.particles.array) { count_particles.innerText = window.pJSDom[0].pJS.particles.array.length; } requestAnimationFrame(update); }; requestAnimationFrame(update);;